import Head from "next/head";
import MySlider from "@/components/custom/slider";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Provider } from "@/components/ui/provider"
import {  Stack, HStack, Box, IconButton, Center  } from "@chakra-ui/react";
import { RxHamburgerMenu } from "react-icons/rx";
import { RiTelegramLine } from "react-icons/ri";
import { IoMailOutline, IoLogoInstagram } from "react-icons/io5";
import MyIcon from "@/components/custom/myicon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Jedasite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Jeda_Logo.svg" />
      </Head>
      <Provider>
          <HStack gap="0" bgColor="black" width="100vw" height="100vh">
            <Box bgColor="#282828" width="4vw" height="100vh" display="flex" flexDirection="column" justifyContent="space-between">
              <IconButton color="#D5D5D5" backgroundColor="transparent" width="4vw" height="4vw" marginTop="4vh" verticalAlign="top">
                <RxHamburgerMenu />
                </IconButton>
              <Stack width="4vw" height="12vw" verticalAlign="bottom" marginBottom="4vh">
                <IconButton width="4vw" height="4vw" color="#D5D5D5" backgroundColor="transparent">
                  <RiTelegramLine />
                </IconButton>
                <IconButton width="4vw" height="4vw" color="#D5D5D5" backgroundColor="transparent">
                  <IoMailOutline />
                </IconButton>
                <IconButton width="4vw" height="4vw" color="#D5D5D5" backgroundColor="transparent">
                  <IoLogoInstagram />
                </IconButton>
              </Stack>
            </Box>
            <Box bgColor="#282828" width="92vw" height="100vh">
              <Box bgColor="#151515" marginTop="4vh" height="92vh" marginBottom="4vh" borderRadius="2vh"></Box>
            </Box>
            <Box bgColor="#282828" width="4vw" height="100vh" justifyContent="space-between">
              <Box width="4vw" height="4vw" marginTop="4vh" verticalAlign="top" display="flex" justifyContent="center">
              <MyIcon height={20} width={20} ></MyIcon>
              </Box >
              <Box justifyContent="center" display="block" width="4vw">
                <MySlider></MySlider>
              </Box>
            </Box>
          </HStack>
        </Provider>
    </>
  );
}
