import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Provider } from "@/components/ui/provider"
import { HStack, Box, Flex } from "@chakra-ui/react"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Jedasite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Provider>
          <HStack gap="0" bgColor="black" width="100vw" height="100vh">
            <Box bgColor="#282828" width="4vw" height="100vh"></Box>
            <Box bgColor="#282828" width="92vw" height="100vh">
              <Box bgColor="#151515" marginTop="4vh" height="92vh" marginBottom="4vh" borderRadius="2vh"></Box>
            </Box>
            <Box bgColor="#282828" width="4vw" height="100vh"></Box>
          </HStack>
        </Provider>
      
    </>
  );
}


